#!/bin/sh
# 2010 pancake//nopcode//org
arps=$(mktemp ${TMPDIR}/arps.XXXXXX)
baseip=$(arp -an| grep ether | head -n 1 | tr '()' '..' | cut -d . -f 2,3,4)
#nmap -sP $baseip.* >/dev/null 2>&1

[ -x /usr/bin/jot ] && alias seq="jot -"

if [ -z "$1" ]; then
	forks=30
	for b in `seq 1 254 $forks` ; do
		for a in `seq $b $(($b+$forks))` ; do
			ping -c 2 ${baseip}.$a >/dev/null 2>&1 &
		done
		sleep 2
	done
fi
arp -an | grep -v incom | sed -e 's,(,,' -e 's,),,' | awk '{print $2" "$4}' > $arps

if [ -f /etc/dhosts ]; then
	hosts=$(grep -v '^#' /etc/dhosts | tr '[A-Z]' '[a-z]' | \
		grep : | awk '{print $2"@"$1}')
else
	echo "Cannot find /etc/dhosts"
	rm -f $arps
	exit 1
fi

for a in $hosts ; do
	name=$(echo $a | cut -d @ -f 1)
	dmac=$(echo $a | cut -d @ -f 2)
	dipa=$(grep $dmac $arps|cut -d ' ' -f 1)
	[ -n "$dipa" ] && echo "$dipa	$name"
done
rm -f $arps
