#!/bin/sh
nam=`echo $@|sed -e 's, ,+,g'`
id=`curl -s "http://weather.yahoo.com/locationWidget/widget/htdocs/locationWidget.php?location=$nam&appId=us_weather" | sed -e 's.,.\n.g' | grep '"id"' | cut -d '"' -f 6`
if [ -z "$id" ]; then
  echo "Invalid location"
  exit 1
fi
curl -s "http://weather.yahooapis.com/forecastrss?w=$id&u=c" | grep :forecast | awk -F '"' '{print $2" "$4"\t"$6"-"$8"\t"$10}'
