#!/bin/sh
#curl -s http://newsrss.bbc.co.uk/weather/forecast/42/Next3DaysRSS.xml
#curl -s "http://news.bbc.co.uk//weather/util/search/WeatherSuggestJSON.json?region=world&search=Barcelona"
#curl -s "http://news.bbc.co.uk/weather/util/Search/Search.json?&search=barcelona%20spain&region=world"
nam=`echo $@|sed -e 's, ,+,g'`
id=`curl -s "http://news.bbc.co.uk/weather/forecast/42/SearchResultsNode.xhtml?&search=$nam&region=world&type=undefined&startIndex=0&lowgraphics=false" | grep weather/forecast | head -n 1 | perl -ne '{/forecast\/(.*)"/;print $1}'`
if [ -z "$id" ]; then
  echo "Invalid location"
  exit 1
fi
curl -s http://newsrss.bbc.co.uk/weather/forecast/$id/Next3DaysRSS.xml | grep title | grep : | cut -c 8- | sed -e 's.:.,.g' -e 's.&.,.g' |awk -F , '{print $1" \t"$2"  \t"$4"-"$8}'
