#!/bin/sh
cd /var/mobile/Library/AddressBook
BD=${BDIR}/addrbook
if [ $? = 0 ]; then
	if [ -z "$1" ]; then
		echo "==> Backup for $0"
		mkdir -p ${BD}
		cp *.sqlitedb ${BD}
	else
		echo "==> Restore $0 from $1"
		cp ${BD}/*.sqlitedb .
	fi
fi
