#!/bin/sh
cd /var/mobile/Library/Calendar
if [ $? = 0 ]; then
	if [ -z "$1" ]; then
		echo "==> Backup for $0"
		mkdir -p ${BDIR}/calendar
		cp Calendar.sqlitedb ${BDIR}/calendar
	else
		echo "==> Restore $0 from $1"
		cp ${BDIR}/calendar/Calendar.sqlitedb .
	fi
fi
