#!/bin/sh
cd /var/mobile/Applications/
cd */CutTheRope.app/..
if [ $? = 0 ]; then
	if [ -z "$1" ]; then
		echo "==> Backup for $0"
		mkdir -p ${BDIR}/cuttherope
		tar czf ${BDIR}/cuttherope/documents.tar.gz Documents
	else
		echo "==> Restore $0 from $1"
		mv Documents Documents.old
		tar xzf ${BDIR}/cuttherope/documents.tar.gz
	fi
fi
