#!/bin/sh
cd /var/mobile/Media/Books/
if [ $? = 0 ]; then
	if [ -z "$1" ]; then
		echo "==> Backup for $0"
		mkdir -p ${BDIR}/ibooks
		tar czf ${BDIR}/ibooks/purchases.tar.gz Purchases
	else
		echo "==> Restore $0 from $1"
		tar xzf ${BDIR}/ibooks/purchases.tar.gz
	fi
fi
