#!/bin/sh
if [ -d /var/mobile/Library/SMS ]; then
cd /var/mobile/Library/SMS
if [ $? = 0 ]; then
	if [ -z "$1" ]; then
		echo "==> Backup for $0"
		mkdir -p ${BDIR}/sms
		cp sms.db ${BDIR}/sms
	else
		echo "==> Restore $0 from $1"
		cp ${BDIR}/sms/sms.db .
	fi
fi
fi
