#!/bin/sh
cd /var/mobile/Applications/
cd */hog.app/..
if [ $? = 0 ]; then
	if [ -z "$1" ]; then
		echo "==> Backup for $0"
		mkdir -p ${BDIR}/sonic4
		cp Documents/sonic4_ep1.dat ${BDIR}/sonic4
	else
		echo "==> Restore $0 from $1"
		cp ${BDIR}/sonic4/sonic4_ep1.dat Documents
	fi
fi
